# Generated by Django 3.2.9 on 2021-11-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211121_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='affliction',
            name='description',
            field=models.TextField(default='No description available', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affliction',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
